   var dependencies = {
    links:
      [
            { "source" : "AppDelegate", "dest" : "_TtC3e2e11AppDelegate" },
            { "source" : "MenuCleanViewController", "dest" : "_TtC3e2e23MenuCleanViewController" },
            { "source" : "Message", "dest" : "_TtC3e2e7Message" },
            { "source" : "MessageDetailViewController", "dest" : "MKMapView" },
            { "source" : "MessageDetailViewController", "dest" : "_TtC3e2e27MessageDetailViewController" },
            { "source" : "MessageList", "dest" : "SwiftObject" },
            { "source" : "MessageTableViewCell", "dest" : "_TtC3e2e20MessageTableViewCell" },
            { "source" : "MessageTableViewController", "dest" : "_TtC3e2e26MessageTableViewController" },
            { "source" : "MessageToolbar", "dest" : "_TtC3e2e14MessageToolbar" },
            { "source" : "PopoverMenuTableViewCell", "dest" : "_TtC3e2e24PopoverMenuTableViewCell" },
            { "source" : "PopoverMenuTableViewController", "dest" : "_TtC3e2e30PopoverMenuTableViewController" },
            { "source" : "PopoverMenuViewController", "dest" : "_TtC3e2e25PopoverMenuViewController" },
            { "source" : "AppDelegate", "dest" : "UnsafeMutablePointer" },
            { "source" : "AppDelegate", "dest" : "Dictionary" },
            { "source" : "AppDelegate", "dest" : "Array" },
            { "source" : "AppDelegate", "dest" : "Int" },
            { "source" : "MenuCleanViewController", "dest" : "Int" },
            { "source" : "Message", "dest" : "UnsafeBufferPointer" },
            { "source" : "Message", "dest" : "Int" },
            { "source" : "MessageDetailViewController", "dest" : "Array" },
            { "source" : "MessageDetailViewController", "dest" : "UnsafeBufferPointer" },
            { "source" : "MessageDetailViewController", "dest" : "Int" },
            { "source" : "MessageList", "dest" : "String" },
            { "source" : "MessageList", "dest" : "Array" },
            { "source" : "MessageList", "dest" : "Bool" },
            { "source" : "MessageList", "dest" : "Message" },
            { "source" : "MessageList", "dest" : "Bool" },
            { "source" : "MessageList", "dest" : "Int" },
            { "source" : "MessageTableViewCell", "dest" : "Int" },
            { "source" : "MessageTableViewController", "dest" : "Array" },
            { "source" : "MessageTableViewController", "dest" : "Int" },
            { "source" : "MessageToolbar", "dest" : "Int" },
            { "source" : "PopoverMenuTableViewCell", "dest" : "Int" },
            { "source" : "PopoverMenuTableViewController", "dest" : "Array" },
            { "source" : "PopoverMenuTableViewController", "dest" : "Int" },
            { "source" : "PopoverMenuViewController", "dest" : "Int" },
         ]
    }
  ;
